
name: Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  create:
    tags:
      - 'release/[0-999].[0-999].[0-999]/'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: exchange
          server-username: EXCHANGE_DEVX_USERNAME
          server-password: EXCHANGE_DEVX_PASSWORD
      - name: Build with maven
        run: |
          REVISION=$(echo $RELEASE_VERSION | cut -d '/' -f 2)
          mvn --batch-mode deploy -Drevision=$REVISION
        env:
          EXCHANGE_DEVX_USERNAME: ${{ secrets.EXCHANGE_DEVX_USERNAME }}
          EXCHANGE_DEVX_PASSWORD: ${{ secrets.EXCHANGE_DEVX_PASSWORD }}

